import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import { SidebarProvider } from "./contexts/sidebarContext";
import TopBar from "./components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="relative flex flex-col w-full h-screen">
            <div className="lg:hidden">
              <TopBar />
            </div>
            <div className="flex flex-row h-full w-full">
              <div className="max-lg:hidden">
                <SideBar />
              </div>
              <div className="border border-black w-full m-4">{children}</div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
